# Generated by Django 5.0.7 on 2024-09-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='story',
            table='stories',
        ),
    ]
