# Generated by Django 5.1 on 2024-08-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
